import mongoose from "mongoose";
import dotenv from "dotenv";
import Genre from "../models/Genre.js";
import Movie from "../models/Movie.js";
import connectDB from "../config/database.js";

dotenv.config();

const seedDatabase = async () => {
  try {
    await connectDB();

    // Clear existing data
    await Genre.deleteMany({});
    await Movie.deleteMany({});

    // Create genres
    const genres = await Genre.create([
      { name: "Action", description: "High-octane action films" },
      { name: "Comedy", description: "Funny and entertaining movies" },
      { name: "Drama", description: "Emotional and compelling stories" },
      { name: "Sci-Fi", description: "Science fiction and futuristic tales" },
      { name: "Horror", description: "Scary and thrilling movies" },
      { name: "Documentary", description: "Factual and educational content" },
      { name: "Adventure", description: "Exciting adventure stories" },
      { name: "Romance", description: "Love stories and romantic tales" },
    ]);

    // Create movies
    const movies = await Movie.create([
      {
        title: "Shang-Chi and the Legend of the Ten Rings",
        description:
          "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        imageUrl: "/movies/shangchi.webp",
        genres: [genres[0]._id],
        year: 2022,
        rating: 8.9,
        duration: 132,
        director: "Destin Daniel Cretton",
        cast: ["Simu Liu", "Awkwafina", "Tony Leung"],
        contentRating: "TV-MA",
        featured: true,
        trending: true,
        popular: true,
        seasons: 2,
        tags: ["Action", "Adventure", "Sci-Fi"],
      },
      {
        title: "Gladiator II",
        description:
          "A sequel to the epic historical drama following the journey of a new hero in ancient Rome.",
        imageUrl:
          "https://www.themoviedb.org/t/p/w1280/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        genres: [genres[0]._id, genres[2]._id],
        year: 2024,
        rating: 8.2,
        duration: 156,
        director: "Ridley Scott",
        cast: ["Paul Mescal", "Denzel Washington"],
        contentRating: "R",
        trending: true,
        tags: ["Action", "Drama", "Historical"],
      },
      {
        title: "Captain America",
        description: "The first Avenger rises to save the world.",
        imageUrl: "/movies/captAmerica.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2011,
        rating: 7.9,
        duration: 124,
        popular: true,
        tags: ["Action", "Sci-Fi"],
      },
      {
        title: "Avatar",
        description:
          "A paraplegic Marine dispatched to the moon Pandora on a unique mission.",
        imageUrl: "/movies/avatar.webp",
        genres: [genres[3]._id, genres[6]._id],
        year: 2009,
        rating: 7.8,
        duration: 162,
        popular: true,
        trending: true,
        tags: ["Sci-Fi", "Adventure", "Fantasy"],
      },
      {
        title: "Oppenheimer",
        description:
          "The story of J. Robert Oppenheimer and the development of the atomic bomb.",
        imageUrl: "/movies/oppenheimer.webp",
        genres: [genres[2]._id],
        year: 2023,
        rating: 8.3,
        duration: 180,
        popular: true,
        featured: true,
        tags: ["Drama", "History", "Biography"],
      },
      {
        title: "The Godfather",
        description:
          "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his youngest son.",
        imageUrl: "/movies/godfather.webp",
        genres: [genres[2]._id],
        year: 1972,
        rating: 9.2,
        duration: 175,
        popular: true,
        trending: true,
        tags: ["Drama", "Crime"],
      },
      {
        title: "Wakanda Forever",
        description: "The kingdom of Wakanda faces a new threat.",
        imageUrl: "/movies/wakanda.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2022,
        rating: 7.3,
        duration: 161,
        popular: true,
        tags: ["Action", "Sci-Fi", "Adventure"],
      },
      {
        title: "300",
        description:
          "King Leonidas of Sparta and a force of 300 men fight the invading Persian army.",
        imageUrl: "/movies/300.webp",
        genres: [genres[0]._id],
        year: 2007,
        rating: 7.6,
        duration: 117,
        trending: true,
        tags: ["Action", "Historical", "War"],
      },
      {
        title: "Babylon",
        description:
          "An ambitious film about the rise and fall of multiple characters during Hollywood's Golden Age.",
        imageUrl: "/movies/babylon.webp",
        genres: [genres[2]._id],
        year: 2022,
        rating: 7.4,
        duration: 189,
        tags: ["Drama", "History"],
      },
      {
        title: "Nobody",
        description: "A man discovers his talent for violence.",
        imageUrl: "/movies/nobody.webp",
        genres: [genres[0]._id],
        year: 2021,
        rating: 7.1,
        duration: 92,
        trending: true,
        tags: ["Action", "Thriller"],
      },
      {
        title: "Blade",
        description:
          "A half-vampire, half-human vampire hunter fights to end the conflict between humans and vampires.",
        imageUrl: "/movies/blade.webp",
        genres: [genres[0]._id, genres[4]._id],
        year: 1998,
        rating: 7.8,
        duration: 121,
        trending: true,
        tags: ["Action", "Horror", "Sci-Fi"],
      },
      {
        title: "The Northman",
        description:
          "A young Viking prince seeks revenge for his father's murder.",
        imageUrl: "/movies/northman.webp",
        genres: [genres[0]._id, genres[2]._id],
        year: 2022,
        rating: 7.6,
        duration: 136,
        trending: true,
        tags: ["Action", "Drama", "Historical"],
      },
      {
        title: "Killers of the Flower Moon",
        description:
          "An investigation into a series of murders of wealthy Osage Nation members.",
        imageUrl: "/movies/killers.webp",
        genres: [genres[2]._id],
        year: 2023,
        rating: 7.2,
        duration: 206,
        popular: true,
        tags: ["Drama", "Crime", "History"],
      },
      {
        title: "Thunderbolts",
        description: "A team of anti-heroes must save the world.",
        imageUrl: "/movies/thunderbolts.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2024,
        rating: 6.9,
        duration: 130,
        trending: true,
        tags: ["Action", "Sci-Fi", "Adventure"],
      },
      {
        title: "Robinhood",
        description: "An outlaw takes from the rich to give to the poor.",
        imageUrl: "/movies/robinhood.webp",
        genres: [genres[0]._id, genres[6]._id],
        year: 2018,
        rating: 6.9,
        duration: 116,
        tags: ["Action", "Adventure", "Drama"],
      },
      {
        title: "Pirates",
        description:
          "A swashbuckling adventure following the exploits of a notorious pirate and his crew.",
        imageUrl:
          "https://www.themoviedb.org/t/p/w1280/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg",
        genres: [genres[0]._id, genres[6]._id],
        year: 2020,
        rating: 7.0,
        duration: 139,
        trending: true,
        tags: ["Action", "Adventure", "Fantasy"],
      },
      {
        title: "Captain America: Civil War",
        description:
          "Political interference in the Avengers' activities causes a rift between former allies.",
        imageUrl:
          "https://www.themoviedb.org/t/p/w1280/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
        genres: [genres[0]._id, genres[3]._id],
        year: 2016,
        rating: 7.8,
        duration: 147,
        popular: true,
        tags: ["Action", "Sci-Fi", "Adventure"],
      },
      {
        title: "Sinners",
        description: "Two men of faith must uncover the truth.",
        imageUrl: "/movies/sinners.webp",
        genres: [genres[2]._id],
        year: 2021,
        rating: 7.2,
        duration: 124,
        tags: ["Drama", "Thriller"],
      },
      {
        title: "Inception",
        description:
          "A skilled thief who steals corporate secrets through dream-sharing technology.",
        imageUrl: "/movies/inception.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2010,
        rating: 8.8,
        duration: 148,
        popular: true,
        featured: true,
        tags: ["Action", "Sci-Fi", "Thriller"],
      },
      {
        title: "The Dark Knight",
        description:
          "Batman faces off against a criminal mastermind known as the Joker.",
        imageUrl: "/movies/darkknight.webp",
        genres: [genres[0]._id, genres[2]._id],
        year: 2008,
        rating: 9.0,
        duration: 152,
        popular: true,
        featured: true,
        trending: true,
        tags: ["Action", "Crime", "Drama"],
      },
      {
        title: "Interstellar",
        description:
          "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        imageUrl: "/movies/interstellar.webp",
        genres: [genres[3]._id, genres[6]._id],
        year: 2014,
        rating: 8.6,
        duration: 169,
        popular: true,
        tags: ["Sci-Fi", "Adventure", "Drama"],
      },
      {
        title: "Dune",
        description:
          "Paul Atreides travels to the dangerous planet Arrakis to ensure the future of his family and people.",
        imageUrl: "/movies/dune.webp",
        genres: [genres[3]._id, genres[6]._id],
        year: 2021,
        rating: 8.0,
        duration: 166,
        popular: true,
        trending: true,
        tags: ["Sci-Fi", "Adventure", "Drama"],
      },
      {
        title: "The Shawshank Redemption",
        description:
          "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        imageUrl: "/movies/shawshank.webp",
        genres: [genres[2]._id],
        year: 1994,
        rating: 9.3,
        duration: 142,
        popular: true,
        featured: true,
        tags: ["Drama", "Crime"],
      },
      {
        title: "Pulp Fiction",
        description:
          "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        imageUrl: "/movies/pulpfiction.webp",
        genres: [genres[2]._id],
        year: 1994,
        rating: 8.9,
        duration: 154,
        popular: true,
        trending: true,
        tags: ["Drama", "Crime"],
      },
      {
        title: "The Avengers",
        description:
          "Earth's mightiest heroes must come together and learn to fight as a team to save the world.",
        imageUrl: "/movies/avengers.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2012,
        rating: 8.0,
        duration: 143,
        popular: true,
        trending: true,
        tags: ["Action", "Sci-Fi", "Adventure"],
      },
      {
        title: "Avengers: Endgame",
        description:
          "After the devastating events, the Avengers assemble once more to reverse Thanos' actions.",
        imageUrl: "/movies/avengersendgame.webp",
        genres: [genres[0]._id, genres[3]._id],
        year: 2019,
        rating: 8.4,
        duration: 181,
        popular: true,
        featured: true,
        trending: true,
        tags: ["Action", "Sci-Fi", "Adventure"],
      },
      {
        title: "The Matrix",
        description:
          "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        imageUrl: "/movies/matrix.webp",
        genres: [genres[3]._id, genres[0]._id],
        year: 1999,
        rating: 8.7,
        duration: 136,
        popular: true,
        trending: true,
        tags: ["Sci-Fi", "Action", "Thriller"],
      },
      {
        title: "Forrest Gump",
        description:
          "The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with an IQ of 75.",
        imageUrl: "/movies/forrestgump.webp",
        genres: [genres[2]._id],
        year: 1994,
        rating: 8.8,
        duration: 142,
        popular: true,
        tags: ["Drama", "Romance", "Comedy"],
      },
      {
        title: "The Pursuit of Happyness",
        description:
          "A struggling salesman takes custody of his son as he tries to build a better life for them both.",
        imageUrl: "/movies/pursuit.webp",
        genres: [genres[2]._id],
        year: 2006,
        rating: 8.5,
        duration: 117,
        popular: true,
        tags: ["Drama", "Biography"],
      },
      {
        title: "Titanic",
        description:
          "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        imageUrl: "/movies/titanic.webp",
        genres: [genres[7]._id, genres[2]._id],
        year: 1997,
        rating: 7.8,
        duration: 194,
        popular: true,
        tags: ["Romance", "Drama", "History"],
      },
      {
        title: "The Notebook",
        description:
          "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.",
        imageUrl: "/movies/notebook.webp",
        genres: [genres[7]._id, genres[2]._id],
        year: 2004,
        rating: 7.8,
        duration: 123,
        tags: ["Romance", "Drama"],
      },
      {
        title: "Fight Club",
        description:
          "An insomniac office worker and a devil-may-care soapmaker form an underground fight club.",
        imageUrl: "/movies/fightclub.webp",
        genres: [genres[2]._id, genres[0]._id],
        year: 1999,
        rating: 8.8,
        duration: 139,
        popular: true,
        trending: true,
        tags: ["Drama", "Action", "Thriller"],
      },
      {
        title: "Se7en",
        description:
          "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
        imageUrl: "/movies/se7en.webp",
        genres: [genres[2]._id, genres[4]._id],
        year: 1995,
        rating: 8.6,
        duration: 127,
        popular: true,
        tags: ["Drama", "Crime", "Mystery"],
      },
      {
        title: "The Silence of the Lambs",
        description:
          "A young FBI cadet must receive the help of an incarcerated cannibal killer to help catch another serial killer.",
        imageUrl: "/movies/silencelambs.webp",
        genres: [genres[2]._id, genres[4]._id],
        year: 1991,
        rating: 8.6,
        duration: 118,
        popular: true,
        tags: ["Drama", "Crime", "Thriller"],
      },
      {
        title: "Parasite",
        description:
          "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        imageUrl: "/movies/parasite.webp",
        genres: [genres[2]._id],
        year: 2019,
        rating: 8.5,
        duration: 132,
        popular: true,
        featured: true,
        trending: true,
        tags: ["Drama", "Thriller"],
      },
      {
        title: "Goodfellas",
        description:
          "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his partner Jimmy.",
        imageUrl: "/movies/goodfellas.webp",
        genres: [genres[2]._id],
        year: 1990,
        rating: 8.7,
        duration: 146,
        popular: true,
        tags: ["Drama", "Crime"],
      },
      {
        title: "Joker",
        description:
          "In Gotham City, a mentally-troubled comedian is disregarded and mistreated by society.",
        imageUrl: "/movies/joker.webp",
        genres: [genres[2]._id, genres[4]._id],
        year: 2019,
        rating: 8.4,
        duration: 122,
        popular: true,
        trending: true,
        tags: ["Drama", "Thriller", "Crime"],
      },
      {
        title: "The Green Mile",
        description:
          "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.",
        imageUrl: "/movies/greenmile.webp",
        genres: [genres[2]._id],
        year: 1999,
        rating: 8.6,
        duration: 189,
        popular: true,
        tags: ["Drama", "Crime", "Fantasy"],
      },
      {
        title: "Gladiator",
        description:
          "A former Roman General sets out to exact vengeance against the Emperor who murdered his family and sent him into slavery.",
        imageUrl: "/movies/gladiator.webp",
        genres: [genres[0]._id, genres[2]._id],
        year: 2000,
        rating: 8.5,
        duration: 155,
        popular: true,
        tags: ["Action", "Drama", "Adventure"],
      },
      {
        title: "The Departed",
        description:
          "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
        imageUrl: "/movies/departed.webp",
        genres: [genres[2]._id],
        year: 2006,
        rating: 8.5,
        duration: 151,
        popular: true,
        tags: ["Drama", "Crime", "Thriller"],
      },
      {
        title: "Requiem for a Dream",
        description:
          "The addictions of four characters intertwine over the course of a year in New York City.",
        imageUrl: "/movies/requiem.webp",
        genres: [genres[2]._id],
        year: 2000,
        rating: 8.4,
        duration: 102,
        tags: ["Drama"],
      },
      {
        title: "Saving Private Ryan",
        description:
          "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
        imageUrl: "/movies/savingprivate.webp",
        genres: [genres[0]._id, genres[2]._id],
        year: 1998,
        rating: 8.6,
        duration: 169,
        popular: true,
        tags: ["War", "Drama", "Action"],
      },
      {
        title: "Back to the Future",
        description:
          "A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend.",
        imageUrl: "/movies/backfuture.webp",
        genres: [genres[3]._id, genres[6]._id],
        year: 1985,
        rating: 8.5,
        duration: 116,
        popular: true,
        tags: ["Sci-Fi", "Adventure", "Comedy"],
      },
      {
        title: "The Lion King",
        description:
          "Lion prince Simba flees his kingdom after the death of his father, only to discover the truth and take back his throne.",
        imageUrl: "/movies/lionking.webp",
        genres: [genres[6]._id],
        year: 1994,
        rating: 8.5,
        duration: 88,
        popular: true,
        tags: ["Adventure", "Animation", "Family"],
      },
      {
        title: "Spirited Away",
        description:
          "During her family's move to the suburbs, a young girl wanders into a mysterious bathhouse and is trapped in the spirit world.",
        imageUrl: "/movies/spiritedaway.webp",
        genres: [genres[6]._id],
        year: 2001,
        rating: 8.6,
        duration: 125,
        popular: true,
        tags: ["Adventure", "Animation", "Fantasy"],
      },
      {
        title: "Toy Story",
        description:
          "A cowboy doll is jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
        imageUrl: "/movies/toystory.webp",
        genres: [genres[1]._id, genres[6]._id],
        year: 1995,
        rating: 8.3,
        duration: 81,
        popular: true,
        tags: ["Comedy", "Animation", "Family"],
      },
      {
        title: "Jaws",
        description:
          "A police chief, a marine scientist, and grizzled fisherman set out to stop an appetite-all-consuming white shark.",
        imageUrl: "/movies/jaws.webp",
        genres: [genres[0]._id, genres[4]._id],
        year: 1975,
        rating: 8.0,
        duration: 124,
        popular: true,
        trending: true,
        tags: ["Action", "Horror", "Thriller"],
      },
      {
        title: "The Sixth Sense",
        description:
          "A boy who communicates with spirits that don't know they're dead seeks the help of a psychologist to improve his life.",
        imageUrl: "/movies/sixthsense.webp",
        genres: [genres[4]._id, genres[2]._id],
        year: 1999,
        rating: 8.2,
        duration: 107,
        popular: true,
        tags: ["Horror", "Drama", "Thriller"],
      },
      {
        title: "The Ring",
        description:
          "A journalist must investigate a mysterious videotape that kills the viewer seven days after watching it.",
        imageUrl: "/movies/ring.webp",
        genres: [genres[4]._id],
        year: 2002,
        rating: 7.1,
        duration: 115,
        trending: true,
        tags: ["Horror", "Thriller"],
      },
      {
        title: "A Clockwork Orange",
        description:
          "A chillingly dystopian look at the far future, society, and what little humanity is worth in it.",
        imageUrl: "/movies/clockworkorange.webp",
        genres: [genres[2]._id, genres[4]._id],
        year: 1971,
        rating: 8.4,
        duration: 136,
        popular: true,
        tags: ["Drama", "Sci-Fi", "Crime"],
      },
      {
        title: "Amélie",
        description:
          "A shy waitress decides to change the lives of those around her for the better, while struggling with her own isolation.",
        imageUrl: "/movies/amelie.webp",
        genres: [genres[1]._id, genres[7]._id],
        year: 2001,
        rating: 8.3,
        duration: 122,
        popular: true,
        tags: ["Comedy", "Romance", "Fantasy"],
      },
      {
        title: "Whiplash",
        description:
          "A promising drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor.",
        imageUrl: "/movies/whiplash.webp",
        genres: [genres[2]._id],
        year: 2014,
        rating: 8.5,
        duration: 107,
        popular: true,
        trending: true,
        tags: ["Drama", "Music"],
      },
    ]);

    console.log("✅ Database seeded successfully!");
    console.log(`📚 ${genres.length} genres created`);
    console.log(`🎬 ${movies.length} movies created`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
};

seedDatabase();
